<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Templates
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

//* Remove default loop
remove_action( 'machina_loop', 'machina_do_loop' );

add_action( 'machina_loop', 'machina_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
function machina_404() {

	echo '<article class="entry">';

		printf( '<h1 class="entry-title">%s</h1>', __( 'Not found, error 404', 'machina' ) );
		echo '<div class="entry-content">';

				echo '<p>' . sprintf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.', 'machina' ), home_url() ) . '</p>';

				echo '<p>' . get_search_form() . '</p>';

			echo '</div>';

		echo '</article>';

}

machina();
