<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Templates
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_action( 'machina_before_loop', 'machina_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function machina_do_search_title() {

	$title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'machina_search_title_text', __( 'Search Results for:', 'machina' ) ), get_search_query() );

	echo apply_filters( 'machina_search_title_output', $title ) . "\n";

}

machina();
