<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Templates
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

//* Output secondary sidebar structure
machina_markup( array(
	'html'   => '<aside %s>',
	'context' => 'sidebar-secondary',
) );

do_action( 'machina_before_sidebar_alt_widget_area' );
do_action( 'machina_sidebar_alt' );
do_action( 'machina_after_sidebar_alt_widget_area' );

machina_markup( array(
	'html' => '</aside>', //* end .sidebar-secondary
) );
