<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Footer
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_action( 'machina_before_footer', 'machina_footer_widget_areas' );
/**
 * Echo the markup necessary to facilitate the footer widget areas.
 *
 * Check for a numerical parameter given when adding theme support - if none is found, then the function returns early.
 *
 * The child theme must style the widget areas.
 *
 * Applies the `machina_footer_widget_areas` filter.
 *
 * @since 1.6.0
 *
 * @uses machina_structural_wrap() Optionally adds wrap with footer-widgets context.
 *
 * @return null Return early if number of widget areas could not be determined, or nothing is added to the first widget area.
 */
function machina_footer_widget_areas() {

	$footer_widgets = get_theme_support( 'machina-footer-widgets' );

	if ( ! $footer_widgets || ! isset( $footer_widgets[0] ) || ! is_numeric( $footer_widgets[0] ) )
		return;

	$footer_widgets = (int) $footer_widgets[0];

	//* Check to see if first widget area has widgets. If not, do nothing. No need to check all footer widget areas.
	if ( ! is_active_sidebar( 'footer-1' ) )
		return;

	$inside  = '';
	$output  = '';
 	$counter = 1;

	while ( $counter <= $footer_widgets ) {

		//* Darn you, WordPress! Gotta output buffer.
		ob_start();
		dynamic_sidebar( 'footer-' . $counter );
		$widgets = ob_get_clean();

		//$inside .= sprintf( '<div class="footer-widgets-%d widget-area">%s</div>', $counter, $widgets );

		/** Dynamically create column classes. */
		$class = 1 == (int) $counter ? 'first ' : '';
		$class .= gs_column_class( $footer_widgets );

		$inside .= sprintf( '<div class="footer-widgets-%1$d widget-area %2$s">%3$s</div>', $counter, $class, $widgets );

		$counter++;

	}

	if ( $inside ) {

		$output .= machina_markup( array(
			'html'   => '<div %s>',
			'context' => 'footer-widgets',
		) );

		$output .= machina_structural_wrap( 'footer-widgets', 'open', 0 );

		$output .= $inside;

		$output .= machina_structural_wrap( 'footer-widgets', 'close', 0 );

		$output .= '</div>';

	}

	echo apply_filters( 'machina_footer_widget_areas', $output, $footer_widgets );

}

add_action( 'machina_footer', 'machina_footer_markup_open', 5 );
/**
 * Echo the opening div tag for the footer.
 *
 * Also optionally adds wrapping div opening tag.
 *
 * @since 1.2.0
 *
 * @uses machina_structural_wrap() Maybe add opening .wrap div tag with footer context.
 * @uses machina_markup()          Apply contextual markup.
 */
function machina_footer_markup_open() {

	machina_markup( array(
		'html'   => '<footer %s>',
		'context' => 'site-footer',
	) );
	machina_structural_wrap( 'footer', 'open' );

}

add_action( 'machina_footer', 'machina_footer_markup_close', 15 );
/**
 * Echo the closing div tag for the footer.
 *
 * Also optionally adds wrapping div closing tag.
 *
 * @since 1.2.0
 *
 * @uses machina_structural_wrap() Maybe add closing .wrap div tag with footer context.
 * @uses machina_markup()          Apply contextual markup.
 */
function machina_footer_markup_close() {

	machina_structural_wrap( 'footer', 'close' );
	machina_markup( array(
		'html'   => '</footer>',
	) );

}

add_filter( 'machina_footer_output', 'do_shortcode', 20 );
add_action( 'machina_footer', 'machina_do_footer' );
/**
 * Echo the contents of the footer.
 *
 * Execute any shortcodes that might be present.
 *
 * Applies `machina_footer_backtotop_text`, `machina_footer_creds_text` and `machina_footer_output` filters.
 *
 * For HTML5 themes, only the credits text is used (back-to-top link is dropped).
 *
 * @todo cleanup function output
 * @since 1.0.1
 *
 */
function machina_do_footer() {

	echo '<div class="creds">' . wpautop( machina_get_option( 'footer-left' ) ) . '</div>';
	echo '<div class="creds">' . wpautop( machina_get_option( 'footer-right' ) ) . '</div>';

}

add_filter( 'machina_footer_scripts', 'do_shortcode' );
add_action( 'wp_footer', 'machina_footer_scripts' );
/**
 * Echo the footer scripts, defined in Theme Settings.
 *
 * Applies the `machina_footer_scripts` filter to the value returns from the footer_scripts option.
 *
 * @since 1.1.0
 *
 * @uses machina_option() Get theme setting value.
 */
function machina_footer_scripts() {

	echo apply_filters( 'machina_footer_scripts', machina_option( 'footer_scripts' ) );

}

add_action( 'wp_footer', 'bfg_ie_font_face_fix', 99 );
/**
 * Forces the main stylesheet to reload on document ready for IE8 and below.
 * This redraws any @font-face fonts, fixing the IE8 font loading bug
 *
 * See: http://stackoverflow.com/questions/9809351/ie8-css-font-face-fonts-only-working-for-before-content-on-over-and-sometimes
 *
 * @since 2.0.13
 */
function bfg_ie_font_face_fix() {

	?><!--[if lt IE 9]>
		<script>
			jQuery(document).ready(function($) {
				var head = document.getElementsByTagName('head')[0],
					style = document.createElement('style');
				style.type = 'text/css';
				style.styleSheet.cssText = ':before,:after{content:none !important';
				head.appendChild(style);
				setTimeout(function(){
					head.removeChild(style);
				}, 0);
			});
		</script>
	<![endif]-->
	<?php

}
