<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Entry
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

/**
 * Restore all default post loop output by re-hooking all default functions.
 *
 * Useful in the event that you need to unhook something in a particular context, but don't want to restore it for all
 * subsequent loop instances.
 *
 * Calls `machina_reset_loops` action after everything has been re-hooked.
 *
 * @since 1.5.0
 *
 * @global array $_machina_loop_args Associative array for grid loop configuration
 */
function machina_reset_loops() {

	//* HTML5 Hooks
	add_action( 'machina_entry_header', 'machina_do_post_format_image', 4 );
	add_action( 'machina_entry_header', 'machina_entry_header_markup_open', 5 );
	add_action( 'machina_entry_header', 'machina_entry_header_markup_close', 15 );
	add_action( 'machina_entry_header', 'machina_do_post_title' );
	add_action( 'machina_entry_header', 'machina_post_info', 12 );

	add_action( 'machina_entry_content', 'machina_do_post_image', 8 );
	add_action( 'machina_entry_content', 'machina_do_post_content' );
	add_action( 'machina_entry_content', 'machina_do_post_content_nav', 12 );
	add_action( 'machina_entry_content', 'machina_do_post_permalink', 14 );

	//Enable Post Navigation
	add_action( 'machina_after_entry_content', 'machina_prev_next_post_nav', 5 );

	add_action( 'machina_entry_footer', 'machina_entry_footer_markup_open', 5 );
	add_action( 'machina_entry_footer', 'machina_entry_footer_markup_close', 15 );
	add_action( 'machina_entry_footer', 'machina_post_meta' );

	add_action( 'machina_after_entry', 'machina_do_author_box_single', 8 );
	add_action( 'machina_after_entry', 'machina_get_comments_template' );

	// Add Widget Area After Post
	add_action('machina_after_post', 'machina_do_after_post_widget');

	//* Pre-HTML5 hooks
	add_action( 'machina_before_post_title', 'machina_do_post_format_image' );
	add_action( 'machina_post_title', 'machina_do_post_title' );
	add_action( 'machina_post_content', 'machina_do_post_image' );
	add_action( 'machina_post_content', 'machina_do_post_content' );
	add_action( 'machina_post_content', 'machina_do_post_permalink' );
	add_action( 'machina_post_content', 'machina_do_post_content_nav' );
	add_action( 'machina_before_post_content', 'machina_post_info' );
	add_action( 'machina_after_post_content', 'machina_post_meta' );
	add_action( 'machina_after_post', 'machina_do_author_box_single' );

	//* Other
	add_action( 'machina_loop_else', 'machina_do_noposts' );
	add_action( 'machina_after_endwhile', 'machina_posts_nav' );

	//* Reset loop args
	global $_machina_loop_args;
	$_machina_loop_args = array();

	do_action( 'machina_reset_loops' );

}

add_filter( 'post_class', 'machina_entry_post_class' );
/**
 * Add `entry` post class, remove `hentry` post class if HTML5.
 *
 * @since 1.9.0
 *
 *
 * @param array Existing post classes.
 *
 * @return array Amended post classes.
 */
function machina_entry_post_class( $classes ) {

	//* Add "entry" to the post class array
	$classes[] = 'entry';

	//* Remove "hentry" from post class array.
	$classes = array_diff( $classes, array( 'hentry' ) );

	return $classes;

}

add_filter( 'post_class', 'machina_custom_post_class', 15 );
/**
 * Add a custom post class, saved as a custom field.
 *
 * @since 1.4.0
 *
 * @uses machina_get_custom_field() Get custom field value.
 *
 * @param array $classes Existing post classes
 * @return array Amended post classes
 */
function machina_custom_post_class( array $classes ) {

	$new_class = machina_get_custom_field( '_machina_custom_post_class' );

	if ( $new_class )
		$classes[] = esc_attr( $new_class );

	return $classes;

}

add_action( 'machina_entry_header', 'machina_do_post_format_image', 4 );
add_action( 'machina_before_post_title', 'machina_do_post_format_image' );
/**
 * Add a post format icon.
 *
 * Adds an image, corresponding to the post format, before the post title.
 *
 * @since 1.4.0
 *
 * @uses CHILD_DIR
 * @uses CHILD_URL
 *
 * @global WP_Post $post Post object.
 *
 * @return null Return early if post formats are not supported, or `machina-post-format-images` is not supported
 */
function machina_do_post_format_image() {

	//* Do nothing if post formats aren't supported
	if ( ! current_theme_supports( 'post-formats' ) || ! current_theme_supports( 'machina-post-format-images' ) )
		return;

	//* Get post format
	$post_format = get_post_format();

	//* If post format is set, look for post format image
	if ( $post_format && file_exists( sprintf( '%s/images/post-formats/%s.png', CHILD_DIR, $post_format ) ) )
		printf( '<a href="%s" title="%s" rel="bookmark"><img src="%s" class="post-format-image" alt="%s" /></a>', get_permalink(), the_title_attribute( 'echo=0' ), sprintf( '%s/images/post-formats/%s.png', CHILD_URL, $post_format ), $post_format );

	//* Else, look for the default post format image
	elseif ( file_exists( sprintf( '%s/images/post-formats/default.png', CHILD_DIR ) ) )
		printf( '<a href="%s" title="%s" rel="bookmark"><img src="%s/images/post-formats/default.png" class="post-format-image" alt="%s" /></a>', get_permalink(), the_title_attribute( 'echo=0' ), CHILD_URL, 'post' );

}

add_action( 'machina_entry_header', 'machina_entry_header_markup_open', 5 );
/**
 * Echo the opening structural markup for the entry header.
 *
 * @since 2.0.0
 *
 * @uses machina_attr() Contextual attributes.
 */
function machina_entry_header_markup_open() {
	printf( '<header %s>', machina_attr( 'entry-header' ) );
}

add_action( 'machina_entry_header', 'machina_entry_header_markup_close', 15 );
/**
 * Echo the closing structural markup for the entry header.
 *
 * @since 2.0.0
 */
function machina_entry_header_markup_close() {
	echo '</header>';
}

add_action( 'machina_entry_header', 'machina_do_post_title' );
add_action( 'machina_post_title', 'machina_do_post_title' );
/**
 * Echo the title of a post.
 *
 * The `machina_post_title_text` filter is applied on the text of the title, while the `machina_post_title_output`
 * filter is applied on the echoed markup.
 *
 * @since 1.1.0
 *
 * @uses machina_get_SEO_option() Get SEO setting value.
 * @uses machina_markup()         Contextual markup.
 *
 * @return null Return early if the length of the title string is zero.
 */
function machina_do_post_title() {

	$title = apply_filters( 'machina_post_title_text', get_the_title() );

	if ( 0 === mb_strlen( $title ) )
		return;

	//* Link it, if necessary
	if ( ! is_singular() && apply_filters( 'machina_link_post_title', true ) )
		$title = sprintf( '<a href="%s" title="%s" rel="bookmark">%s</a>', get_permalink(), the_title_attribute( 'echo=0' ), $title );

	//* Wrap in H1 on singular pages
	$wrap = is_singular() ? 'h1' : 'h2';

	//* Also, if semantic headings, wrap in H1
	$wrap = machina_get_seo_option( 'semantic_headings' ) ? 'h1' : $wrap;

	//* Build the output
	$output = machina_markup( array(
		'html5'   => "<{$wrap} %s>",
		'xhtml'   => sprintf( '<%s class="entry-title">%s</%s>', $wrap, $title, $wrap ),
		'context' => 'entry-title',
		'echo'    => false,
	) );

	$output .= "{$title}</{$wrap}>";

	echo apply_filters( 'machina_post_title_output', "$output \n" );

}

add_filter( 'machina_post_info', 'do_shortcode', 20 );
add_action( 'machina_entry_header', 'machina_post_info', 12 );
add_action( 'machina_before_post_content', 'machina_post_info' );
/**
 * Echo the post info (byline) under the post title.
 *
 * Doesn't do post info on pages.
 *
 * The post info makes use of several shortcodes by default, and the whole output is filtered via `machina_post_info`
 * before echoing.
 *
 * @since 0.2.3
 *
 * @uses machina_markup() Contextual markup.
 *
 * @global WP_Post $post Post object.
 *
 * @return null Return early if on a page.
 */
function machina_post_info() {

	global $post;

	if ( 'page' === get_post_type( $post->ID ) )
		return;

	$post_info = apply_filters( 'machina_post_info', '[post_date] ' . __( 'by', 'machina' ) . ' [post_author_posts_link] [post_comments] [post_edit]' );

	machina_markup( array(
		'html5' => sprintf( '<p class="entry-meta">%s</p>', $post_info ),
		'xhtml' => sprintf( '<div class="post-info">%s</div>', $post_info ),
	) );

}

add_filter( 'machina_post_info', 'post_info_filter' );

function post_info_filter( $output ) {

	return machina_get_option( 'post_info' );

}


add_action( 'machina_entry_content', 'machina_do_post_image', 8 );
add_action( 'machina_post_content', 'machina_do_post_image' );
/**
 * Echo the post image on archive pages.
 *
 * If this an archive page and the option is set to show thumbnail, then it gets the image size as per the theme
 * setting, wraps it in the post permalink and echoes it.
 *
 * @since 1.1.0
 *
 * @uses machina_get_option() Get theme setting value.
 * @uses machina_get_image()  Return an image pulled from the media library.
 * @uses machina_parse_attr() Return contextual attributes.
 */
function machina_do_post_image() {

	if ( ! is_singular() && machina_get_option( 'content_archive_thumbnail' ) ) {
		$img = machina_get_image( array(
			'format'  => 'html',
			'size'    => machina_get_option( 'image_size' ),
			'context' => 'archive',
			'attr'    => machina_parse_attr( 'entry-image' ),
		) );

		if ( ! empty( $img ) )
			printf( '<a href="%s" title="%s">%s</a>', get_permalink(), the_title_attribute( 'echo=0' ), $img );
	}

}

add_action( 'machina_entry_content', 'machina_do_post_content' );
add_action( 'machina_post_content', 'machina_do_post_content' );
/**
 * Echo the post content.
 *
 * On single posts or pages it echoes the full content, and optionally the trackback string if enabled. On single pages,
 * also adds the edit link after the content.
 *
 * Elsewhere it displays either the excerpt, limited content, or full content.
 *
 * Applies the `machina_edit_post_link` filter.
 *
 * @since 1.1.0
 *
 * @uses machina_get_option() Get theme setting value.
 * @uses the_content_limit()  Limited content.
 *
 * @global WP_Post $post Post object.
 */
function machina_do_post_content() {

	global $post;

	if ( is_singular() ) {
		the_content();

		if ( is_single() && 'open' === get_option( 'default_ping_status' ) && post_type_supports( $post->post_type, 'trackbacks' ) ) {
			echo '<!--';
			trackback_rdf();
			echo '-->' . "\n";
		}

		if ( is_page() && apply_filters( 'machina_edit_post_link', true ) )
			edit_post_link( __( '(Edit)', 'machina' ), '', '' );
	}
	elseif ( 'excerpts' === machina_get_option( 'content_archive' ) ) {
		the_excerpt();
	}
	else {
		if ( machina_get_option( 'content_archive_limit' ) )
			the_content_limit( (int) machina_get_option( 'content_archive_limit' ), __( '[Read more...]', 'machina' ) );
		else
			the_content( __( '[Read more...]', 'machina' ) );
	}

}

add_action( 'machina_entry_content', 'machina_do_post_content_nav', 12 );
add_action( 'machina_post_content', 'machina_do_post_content_nav' );
/**
 * Display page links for paginated posts (i.e. includes the <!--nextpage--> Quicktag one or more times).
 *
 * @since 2.0.0
 *
 * @uses machina_markup() Contextual markup.
 */
function machina_do_post_content_nav() {

	wp_link_pages( array(
		'before' => machina_markup( array(
				'html5'   => '<div %s>',
				'xhtml'   => '<p class="pages">',
				'context' => 'entry-pagination',
				'echo'    => false,
			) ) . __( 'Pages:', 'machina' ),
		'after'  => '</div>',
	) );

}

add_action( 'machina_entry_content', 'machina_do_post_permalink', 14 );
add_action( 'machina_post_content', 'machina_do_post_permalink' );
/**
 * Show permalink if no title.
 *
 * If the entry has no title, this is a way to display a link to the full post.
 *
 * Applies the `machina_post_permalink` filter.
 *
 * @since 2.0.0
 */
function machina_do_post_permalink() {

	//* Don't show on singular views, or if the entry has a title
	if ( is_singular() || get_the_title() )
		return;

	$permalink = get_permalink();

	echo apply_filters( 'machina_post_permalink', sprintf( '<p class="entry-permalink"><a href="%s" title="%s" rel="bookmark">%s</a></p>', esc_url( $permalink ), __( 'Permalink', 'machina' ), esc_html( $permalink ) ) );

}

add_action( 'machina_loop_else', 'machina_do_noposts' );
/**
 * Echo filterable content when there are no posts to show.
 *
 * The applied filter is `machina_noposts_text`.
 *
 * @since 1.1.0
 */
function machina_do_noposts() {

	printf( '<div class="entry"><p>%s</p></div>', apply_filters( 'machina_noposts_text', __( 'Sorry, no content matched your criteria.', 'machina' ) ) );

}

add_action( 'machina_entry_footer', 'machina_entry_footer_markup_open', 5 );
/**
 * Echo the opening structural markup for the entry footer.
 *
 * @since 2.0.0
 *
 * @uses machina_attr() Contextual attributes.
 */
function machina_entry_footer_markup_open() {

	if ( 'post' === get_post_type() )
		printf( '<footer %s>', machina_attr( 'entry-footer' ) );

}

add_action( 'machina_entry_footer', 'machina_entry_footer_markup_close', 15 );
/**
 * Echo the closing structural markup for the entry footer.
 *
 * @since 2.0.0
 */
function machina_entry_footer_markup_close() {

	if ( 'post' === get_post_type() )
		echo '</footer>';

}

add_filter( 'machina_post_meta', 'do_shortcode', 20 );
add_action( 'machina_entry_footer', 'machina_post_meta' );
add_action( 'machina_after_post_content', 'machina_post_meta' );
/**
 * Echo the post meta after the post content.
 *
 * Doesn't do post meta on pages.
 *
 * The post info makes use of a couple of shortcodes by default, and the whole output is filtered via
 * `machina_post_meta` before echoing.
 *
 * @since 0.2.3
 *
 * @uses machina_markup() Contextual markup.
 *
 * @global WP_Post $post Post object.
 *
 * @return null Return early if on a page
 */
function machina_post_meta() {

	global $post;

	if ( 'page' === get_post_type( $post->ID ) )
		return;

	$post_meta = apply_filters( 'machina_post_meta', '[post_categories] [post_tags]' );

	machina_markup( array(
		'html5' => sprintf( '<p class="entry-meta">%s</p>', $post_meta ),
		'xhtml' => sprintf( '<div class="post-meta">%s</div>', $post_meta ),
	) );

}

add_filter( 'machina_post_meta', 'post_meta_filter' );

function post_meta_filter( $output ) {

	return machina_get_option( 'post_meta' );

}

add_action( 'machina_after_entry', 'machina_do_author_box_single', 8 );
add_action( 'machina_after_post', 'machina_do_author_box_single' );
/**
 * Conditionally add the author box after single posts or pages.
 *
 * @since 1.0.0
 *
 * @uses machina_author_box() Echo the author box.
 *
 * @return null Return early if not a single post or page.
 */
function machina_do_author_box_single() {

	if ( ! is_single() )
		return;

	if ( get_the_author_meta( 'machina_author_box_single', get_the_author_meta( 'ID' ) ) )
		machina_author_box( 'single' );

}

/**
 * Echo the the author box and its contents.
 *
 * The title is filterable via `machina_author_box_title`, and the gravatar size is filterable via
 * `machina_author_box_gravatar_size`.
 *
 * The final output is filterable via `machina_author_box`, which passes many variables through.
 *
 * @since 1.3.0
 *
 * @uses machina_attr()  Contextual attributes.
 *
 * @global WP_User $authordata Author (user) object.
 *
 * @param string $context Optional. Allows different author box markup for different contexts, specifically 'single'.
 *                        Default is empty string.
 * @param bool   $echo    Optional. If true, the author box will echo. If false, it will be returned.
 *
 * @return string HTML for author box.
 */
function machina_author_box( $context = '', $echo = true ) {

	global $authordata;

	$authordata    = is_object( $authordata ) ? $authordata : get_userdata( get_query_var( 'author' ) );
	$gravatar_size = apply_filters( 'machina_author_box_gravatar_size', 70, $context );
	$gravatar      = get_avatar( get_the_author_meta( 'email' ), $gravatar_size );
	$description   = wpautop( get_the_author_meta( 'description' ) );

	//* The author box markup, contextual

		$title = apply_filters( 'machina_author_box_title', sprintf( '%s <span itemprop="name">%s</span>', __( 'About', 'machina' ), get_the_author() ), $context );

		$pattern  = sprintf( '<section %s>', machina_attr( 'author-box' ) );
		$pattern .= '%s<h1 class="author-box-title">%s</h1>';
		$pattern .= '<div class="author-box-content" itemprop="description">%s</div>';
		$pattern .= '</section>';




	$output = apply_filters( 'machina_author_box', sprintf( $pattern, $gravatar, $title, $description ), $context, $pattern, $gravatar, $title, $description );

	if ( $echo )
		echo $output;
	else
		return $output;

}

add_action( 'machina_after_endwhile', 'machina_posts_nav' );
/**
 * Conditionally echo archive pagination in a format dependent on chosen setting.
 *
 * This is shown at the end of archives to get to another page of entries.
 *
 * @since 0.2.3
 *
 * @uses machina_get_option()            Get theme setting value.
 * @uses machina_prev_next_posts_nav()   Prev and Next links.
 * @uses machina_numeric_posts_nav()     Numbered links.
 */
function machina_posts_nav() {

	if ( 'numeric' === machina_get_option( 'posts_nav' ) )
		machina_numeric_posts_nav();
	else
		machina_prev_next_posts_nav();

}

/**
 * Echo archive pagination in Previous Posts / Next Posts format.
 *
 * Applies `machina_prev_link_text` and `machina_next_link_text` filters.
 *
 * @since 0.2.2
 */
function machina_prev_next_posts_nav() {

	$prev_link = get_previous_posts_link( apply_filters( 'machina_prev_link_text', '&#x000AB;' . __( 'Previous Page', 'machina' ) ) );
	$next_link = get_next_posts_link( apply_filters( 'machina_next_link_text', __( 'Next Page', 'machina' ) . '&#x000BB;' ) );

	$prev = $prev_link ? '<div class="pagination-previous alignleft">' . $prev_link . '</div>' : '';
	$next = $next_link ? '<div class="pagination-next alignright">' . $next_link . '</div>' : '';

	$nav = machina_markup( array(
		'html5'   => '<div %s>',
		'xhtml'   => '<div class="navigation">',
		'context' => 'archive-pagination',
		'echo'    => false,
	) );

	$nav .= $prev;
	$nav .= $next;
	$nav .= '</div>';

	if ( $prev || $next )
		echo $nav;
}

/**
 * Echo archive pagination in page numbers format.
 *
 * Applies the `machina_prev_link_text` and `machina_next_link_text` filters.
 *
 * The links, if needed, are ordered as:
 *
 *  * previous page arrow,
 *  * first page,
 *  * up to two pages before current page,
 *  * current page,
 *  * up to two pages after the current page,
 *  * last page,
 *  * next page arrow.
 *
 * @since 0.2.3
 *
 * @global WP_Query $wp_query Query object.
 *
 * @return null Return early if on a single post or page, or only one page present.
 */
function machina_numeric_posts_nav() {

	if( is_singular() )
		return;

	global $wp_query;

	//* Stop execution if there's only 1 page
	if( $wp_query->max_num_pages <= 1 )
		return;

	$paged = get_query_var( 'paged' ) ? absint( get_query_var( 'paged' ) ) : 1;
	$max   = intval( $wp_query->max_num_pages );

	//* Add current page to the array
	if ( $paged >= 1 )
		$links[] = $paged;

	//* Add the pages around the current page to the array
	if ( $paged >= 3 ) {
		$links[] = $paged - 1;
		$links[] = $paged - 2;
	}

	if ( ( $paged + 2 ) <= $max ) {
		$links[] = $paged + 2;
		$links[] = $paged + 1;
	}

	machina_markup( array(
		'html5'   => '<div %s>',
		'xhtml'   => '<div class="navigation">',
		'context' => 'archive-pagination',
	) );

	echo '<ul>';

	//* Previous Post Link
	if ( get_previous_posts_link() )
		printf( '<li class="pagination-previous">%s</li>' . "\n", get_previous_posts_link( apply_filters( 'machina_prev_link_text', '&#x000AB;' . __( 'Previous Page', 'machina' ) ) ) );

	//* Link to first page, plus ellipses if necessary
	if ( ! in_array( 1, $links ) ) {

		$class = 1 == $paged ? ' class="active"' : '';

		printf( '<li%s><a href="%s">%s</a></li>' . "\n", $class, esc_url( get_pagenum_link( 1 ) ), '1' );

		if ( ! in_array( 2, $links ) )
			echo '<li class="pagination-omission">&#x02026;</li>';

	}

	//* Link to current page, plus 2 pages in either direction if necessary
	sort( $links );
	foreach ( (array) $links as $link ) {
		$class = $paged == $link ? ' class="active"' : '';
		printf( '<li%s><a href="%s">%s</a></li>' . "\n", $class, esc_url( get_pagenum_link( $link ) ), $link );
	}

	//* Link to last page, plus ellipses if necessary
	if ( ! in_array( $max, $links ) ) {

		if ( ! in_array( $max - 1, $links ) )
			echo '<li class="pagination-omission">&#x02026;</li>' . "\n";

		$class = $paged == $max ? ' class="active"' : '';
		printf( '<li%s><a href="%s">%s</a></li>' . "\n", $class, esc_url( get_pagenum_link( $max ) ), $max );

	}

	//* Next Post Link
	if ( get_next_posts_link() )
		printf( '<li class="pagination-next">%s</li>' . "\n", get_next_posts_link( apply_filters( 'machina_next_link_text', __( 'Next Page', 'machina' ) . '&#x000BB;' ) ) );

	echo '</ul></div>' . "\n";

}

/**
 * Display links to previous and next post, from a single post.
 *
 * @since 1.5.1
 *
 * @return null Return early if not a post.
 */
function machina_prev_next_post_nav() {

	if ( ! is_singular( 'post' ) )
		return;

	machina_markup( array(
		'html5'   => '<div %s>',
		'xhtml'   => '<div class="navigation">',
		'context' => 'adjacent-entry-pagination',
	) );

	echo '<div class="pagination-previous alignleft">';
	previous_post_link();
	echo '</div>';

	echo '<div class="pagination-next alignright">';
	next_post_link();
	echo '</div>';

	echo '</div>';

}



add_filter( 'the_content', 'bfg_remove_ptags_on_images' );
/**
 * Remove <p> tags from around images
 *
 * See: http://css-tricks.com/snippets/wordpress/remove-paragraph-tags-from-around-images/
 *
 * @since 1.x
 */
function bfg_remove_ptags_on_images( $content ){

	return preg_replace( '/<p>\s*(<a .*>)?\s*(<img .* \/>)\s*(<\/a>)?\s*<\/p>/iU', '\1\2\3', $content );

}

add_filter( 'gallery_style', 'bfg_gallery_style' );
/**
 * Remove the injected styles for the [gallery] shortcode
 *
 * @since 1.x
 */
function bfg_gallery_style( $css ) {

	return preg_replace( "!<style type='text/css'>(.*?)</style>!s", '', $css );

}

// add_filter( 'the_content_more_link', 'bfg_more_tag_excerpt_link' );
/**
 * Customize the excerpt text, when using the <!--more--> tag
 *
 *
 * @since 2.0.16
 */
function bfg_more_tag_excerpt_link() {

	return ' <a class="more-link" href="' . get_permalink() . '">Read more &rarr;</a>';

}

// add_filter( 'excerpt_more', 'bfg_truncated_excerpt_link' );
// add_filter( 'get_the_content_more_link', 'bfg_truncated_excerpt_link' );
/**
 * Customize the excerpt text, when using automatic truncation
 *
 * @since 2.0.16
 */
function bfg_truncated_excerpt_link() {

	return '... <a class="more-link" href="' . get_permalink() . '">Read more &rarr;</a>';

}

// add_filter ( 'machina_prev_link_text' , 'bfg_prev_link_text' );
/**
 * Customize the post navigation prev text
 * (Only applies to the 'Previous/Next' Post Navigation Technique, set in Machina > Theme Options)
 *
 * @since 2.0.0
 */
function bfg_prev_link_text( $text ) {

    return html_entity_decode('&#10216;') . ' ';

}

// add_filter ( 'machina_next_link_text' , 'bfg_next_link_text' );
/**
 * Customize the post navigation next text
 * (Only applies to the 'Previous/Next' Post Navigation Technique, set in Machina > Theme Options)
 *
 * @since 2.0.0
 */
function bfg_next_link_text( $text ) {

    return ' ' . html_entity_decode('&#10217;');

}

//* Hook after-entru widget to single posts (outside post class)
add_action( 'machina_after_entry', 'bg_after_entry_widget', 9  );
function bg_after_entry_widget() {
	if ( is_single() && is_active_sidebar( 'after-post' ) ) {
		echo '<div class="after-post"><div class="wrap">';
		dynamic_sidebar( 'after-post' );
		echo '</div></div>';
	}
}