<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Search
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_filter( 'get_search_form', 'machina_search_form' );
/**
 * Replace the default search form with a Machina-specific form.
 *
 * The exact output depends on whether the child theme supports HTML5 or not.
 *
 * Applies the `machina_search_text`, `machina_search_button_text`, `machina_search_form_label` and
 * `machina_search_form` filters.
 *
 * @since 0.2.0
 *
 * @uses machina_html5() Check for HTML5 support.
 *
 * @return string HTML markup.
 */
function machina_search_form() {
	$search_text = get_search_query() ? apply_filters( 'the_search_query', get_search_query() ) : apply_filters( 'machina_search_text', __( 'Search this website', 'machina' ) . '&#x02026;' );

	$button_text = apply_filters( 'machina_search_button_text', esc_attr__( 'Search', 'machina' ) );

	$onfocus = "if ('" . esc_js( $search_text ) . "' === this.value) {this.value = '';}";
	$onblur  = "if ('' === this.value) {this.value = '" . esc_js( $search_text ) . "';}";

	//* Empty label, by default. Filterable.
	$label = apply_filters( 'machina_search_form_label', '' );

	if ( machina_html5() )
		$form = sprintf( '<form method="get" class="search-form" action="%s" role="search">%s<input type="search" name="s" placeholder="%s" /><input type="submit" value="%s" /></form>', home_url( '/' ), esc_html( $label ), esc_attr( $search_text ), esc_attr( $button_text ) );
	else
		$form = sprintf( '<form method="get" class="searchform search-form" action="%s" role="search" >%s<input type="text" value="%s" name="s" class="s search-input" onfocus="%s" onblur="%s" /><input type="submit" class="searchsubmit search-submit" value="%s" /></form>', home_url( '/' ), esc_html( $label ), esc_attr( $search_text ), esc_attr( $onfocus ), esc_attr( $onblur ), esc_attr( $button_text ) );

	return apply_filters( 'machina_search_form', $form, $search_text, $button_text, $label );

}

// add_filter( 'machina_search_text', 'bfg_search_text' );
/**
 * Customize the search form input box text
 *
 * See: http://www.briangardner.com/code/customize-search-form/
 *
 * @since 2.0.0
 */
function bfg_search_text() {
	return esc_attr( 'Search Text Goes Here...' );
}

// add_filter( 'machina_search_button_text', 'bfg_search_button_text' );
/**
 * Customize the search form input button text
 *
 *
 * @since 2.0.0
 */
function bfg_search_button_text( $text ) {
	return esc_attr( 'Click Here...' );
}

// add_action( 'template_redirect', 'bfg_redirect_single_search_result' );
/**
 * Redirect to the result itself, if only one search result is returned
 *
 * See: http://www.developerdrive.com/2013/07/5-quick-and-easy-tricks-to-improve-your-wordpress-theme/
 *
 * @since 2.0.5
 */
function bfg_redirect_single_search_result() {

    if( is_search() ) {
        global $wp_query;

        if( $wp_query->post_count == 1) {
            wp_redirect( get_permalink( $wp_query->posts['0']->ID ) );
        }
    }

}
