<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Sidebars
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_action( 'machina_sidebar', 'machina_do_sidebar' );
/**
 * Echo primary sidebar default content.
 *
 * Only shows if sidebar is empty, and current user has the ability to edit theme options (manage widgets).
 *
 * @since 1.2.0
 *
 * @uses machina_default_widget_area_content() Template for default widget are content.
 */
function machina_do_sidebar() {

	if ( ! dynamic_sidebar( 'sidebar' ) && current_user_can( 'edit_theme_options' )  ) {
		machina_default_widget_area_content( __( 'Primary Sidebar Widget Area', 'machina' ) );
	}

}

add_action( 'machina_sidebar_alt', 'machina_do_sidebar_alt' );
/**
 * Echo alternate sidebar default content.
 *
 * Only shows if sidebar is empty, and current user has the ability to edit theme options (manage widgets).
 *
 * @since 1.2.0
 *
 * @uses machina_default_widget_area_content() Template for default widget are content.
 */
function machina_do_sidebar_alt() {

	if ( ! dynamic_sidebar( 'sidebar-alt' ) && current_user_can( 'edit_theme_options' ) ) {
		machina_default_widget_area_content( __( 'Secondary Sidebar Widget Area', 'machina' ) );
	}

}

/**
 * Template for default widget area content.
 *
 * @since 2.0.0
 *
 * @param string $name Name of the widget area e.g. `__( 'Secondary Sidebar Widget Area', 'yourtextdomain' )`.
 */
function machina_default_widget_area_content( $name ) {

	echo '<section class="widget widget_text">';
	echo '<div class="widget-wrap">';

		printf( '<h4 class="widgettitle">%s</h4>', esc_html( $name ) );
		echo '<div class="textwidget"><p>';

			printf( __( 'This is the %s. You can add content to this area by visiting your <a href="%s">Widgets Panel</a> and adding new widgets to this area.', 'machina' ), $name, admin_url( 'widgets.php' ) );

		echo '</p></div>';

	echo '</div>';
	echo '</section>';

}

/**
 * Allow shortcodes in text widgets
 *
 * @since 2.0.0
 */
// add_filter( 'widget_text', 'do_shortcode' );

add_action( 'wp_head', 'bfg_remove_recent_comments_widget_styles', 1 );
/**
 * Remove 'Recent Comments' widget injected styles
 *
 * @since 1.x
 */
function bfg_remove_recent_comments_widget_styles() {

	global $wp_widget_factory;
	if (isset($wp_widget_factory->widgets['WP_Widget_Recent_Comments'])) {
		remove_action( 'wp_head', array($wp_widget_factory->widgets['WP_Widget_Recent_Comments'], 'recent_comments_style' ));
	}

}
