<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Admin
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_action( 'admin_menu', 'machina_add_inpost_seo_box' );
/**
 * Register a new meta box to the post or page edit screen, so that the user can set SEO options on a per-post or
 * per-page basis.
 *
 * If the post type does not support machina-seo, then the SEO meta box will not be added.
 *
 * @since 0.1.3
 *
 * @see machina_inpost_seo_box() Generates the content in the meta box.
 */
function machina_add_inpost_seo_box() {

	if ( machina_detect_seo_plugins() )
		return;

	foreach ( (array) get_post_types( array( 'public' => true ) ) as $type ) {
		if ( post_type_supports( $type, 'machina-seo' ) )
			add_meta_box( 'machina_inpost_seo_box', __( 'Theme SEO Settings', 'machina' ), 'machina_inpost_seo_box', $type, 'normal', 'default' );
	}

}

/**
 * Callback for in-post SEO meta box.
 *
 * @since 0.1.3
 *
 * @uses machina_get_custom_field() Get custom field value.
 */
function machina_inpost_seo_box() {

	wp_nonce_field( 'machina_inpost_seo_save', 'machina_inpost_seo_nonce' );
	?>

	<p><label for="machina_title"><b><?php _e( 'Custom Document Title', 'machina' ); ?></b> <abbr title="&lt;title&gt; Tag">[?]</abbr> <span class="hide-if-no-js"><?php printf( __( 'Characters Used: %s', 'machina' ), '<span id="machina_title_chars">'. mb_strlen( machina_get_custom_field( '_machina_title' ) ) .'</span>' ); ?></span></label></p>
	<p><input class="large-text" type="text" name="machina_seo[_machina_title]" id="machina_title" value="<?php echo esc_attr( machina_get_custom_field( '_machina_title' ) ); ?>" /></p>

	<p><label for="machina_description"><b><?php _e( 'Custom Post/Page Meta Description', 'machina' ); ?></b> <abbr title="&lt;meta name=&quot;description&quot; /&gt;">[?]</abbr> <span class="hide-if-no-js"><?php printf( __( 'Characters Used: %s', 'machina' ), '<span id="machina_description_chars">'. mb_strlen( machina_get_custom_field( '_machina_description' ) ) .'</span>' ); ?></span></label></p>
	<p><textarea class="large-text" name="machina_seo[_machina_description]" id="machina_description" rows="4" cols="4"><?php echo esc_textarea( machina_get_custom_field( '_machina_description' ) ); ?></textarea></p>

	<p><label for="machina_keywords"><b><?php _e( 'Custom Post/Page Meta Keywords, comma separated', 'machina' ); ?></b> <abbr title="&lt;meta name=&quot;keywords&quot; /&gt;">[?]</abbr></label></p>
	<p><input class="large-text" type="text" name="machina_seo[_machina_keywords]" id="machina_keywords" value="<?php echo esc_attr( machina_get_custom_field( '_machina_keywords' ) ); ?>" /></p>

	<p><label for="machina_canonical"><b><?php _e( 'Custom Canonical URL', 'machina' ); ?></b> <a href="http://www.mattcutts.com/blog/canonical-link-tag/" target="_blank" title="&lt;link rel=&quot;canonical&quot; /&gt;">[?]</a></label></p>
	<p><input class="large-text" type="text" name="machina_seo[_machina_canonical_uri]" id="machina_canonical" value="<?php echo esc_url( machina_get_custom_field( '_machina_canonical_uri' ) ); ?>" /></p>

	<p><label for="machina_redirect"><b><?php _e( 'Custom Redirect URL', 'machina' ); ?></b> <a href="http://www.google.com/support/webmasters/bin/answer.py?hl=en&amp;answer=93633" target="_blank" title="301 Redirect">[?]</a></label></p>
	<p><input class="large-text" type="text" name="machina_seo[redirect]" id="machina_redirect" value="<?php echo esc_url( machina_get_custom_field( 'redirect' ) ); ?>" /></p>

	<br />

	<p><b><?php _e( 'Robots Meta Settings', 'machina' ); ?></b></p>

	<p>
		<label for="machina_noindex"><input type="checkbox" name="machina_seo[_machina_noindex]" id="machina_noindex" value="1" <?php checked( machina_get_custom_field( '_machina_noindex' ) ); ?> />
		<?php printf( __( 'Apply %s to this post/page', 'machina' ), machina_code( 'noindex' ) ); ?> <a href="http://yoast.com/articles/robots-meta-tags/" target="_blank">[?]</a></label><br />

		<label for="machina_nofollow"><input type="checkbox" name="machina_seo[_machina_nofollow]" id="machina_nofollow" value="1" <?php checked( machina_get_custom_field( '_machina_nofollow' ) ); ?> />
		<?php printf( __( 'Apply %s to this post/page', 'machina' ), machina_code( 'nofollow' ) ); ?> <a href="http://yoast.com/articles/robots-meta-tags/" target="_blank">[?]</a></label><br />

		<label for="machina_noarchive"><input type="checkbox" name="machina_seo[_machina_noarchive]" id="machina_noarchive" value="1" <?php checked( machina_get_custom_field( '_machina_noarchive' ) ); ?> />
		<?php printf( __( 'Apply %s to this post/page', 'machina' ), machina_code( 'noarchive' ) ); ?> <a href="http://yoast.com/articles/robots-meta-tags/" target="_blank">[?]</a></label>
	</p>
	<?php

}

add_action( 'save_post', 'machina_inpost_seo_save', 1, 2 );
/**
 * Save the SEO settings when we save a post or page.
 *
 * Some values get sanitized, the rest are pulled from identically named subkeys in the $_POST['machina_seo'] array.
 *
 * @since 0.1.3
 *
 * @uses machina_save_custom_fields() Perform checks and saves post meta / custom field data to a post or page.
 *
 * @param integer  $post_id Post ID.
 * @param stdClass $post    Post object.
 *
 * @return mixed Returns post id if permissions incorrect, null if doing autosave, ajax or future post, false if update
 *               or delete failed, and true on success.
 */
function machina_inpost_seo_save( $post_id, $post ) {

	if ( ! isset( $_POST['machina_seo'] ) )
		return;

	//* Merge user submitted options with fallback defaults
	$data = wp_parse_args( $_POST['machina_seo'], array(
		'_machina_title'         => '',
		'_machina_description'   => '',
		'_machina_keywords'      => '',
		'_machina_canonical_uri' => '',
		'redirect'               => '',
		'_machina_noindex'       => 0,
		'_machina_nofollow'      => 0,
		'_machina_noarchive'     => 0,
	) );

	//* Sanitize the title, description, and tags
	foreach ( (array) $data as $key => $value ) {
		if ( in_array( $key, array( '_machina_title', '_machina_description', '_machina_keywords' ) ) )
			$data[ $key ] = strip_tags( $value );
	}

	machina_save_custom_fields( $data, 'machina_inpost_seo_save', 'machina_inpost_seo_nonce', $post );

}

add_action( 'admin_menu', 'machina_add_inpost_scripts_box' );
/**
 * Register a new meta box to the post or page edit screen, so that the user can apply scripts on a per-post or
 * per-page basis.
 *
 * The scripts field was previously part of the SEO meta box, and was therefore hidden when an SEO plugin was active.
 *
 * @since 2.0.0
 *
 * @see machina_inpost_scripts_box() Generates the content in the meta box.
 */
function machina_add_inpost_scripts_box() {

	//* If user doesn't have unfiltered html capability, don't show this box
	if ( ! current_user_can( 'unfiltered_html' ) )
		return;

	foreach ( (array) get_post_types( array( 'public' => true ) ) as $type ) {
		if ( post_type_supports( $type, 'machina-scripts' ) )
			add_meta_box( 'machina_inpost_scripts_box', __( 'Scripts', 'machina' ), 'machina_inpost_scripts_box', $type, 'normal', 'low' );
	}

}

/**
 * Callback for in-post Scripts meta box.
 *
 * @since 2.0.0
 *
 * @uses machina_get_custom_field() Get custom field value.
 */
function machina_inpost_scripts_box() {

	wp_nonce_field( 'machina_inpost_scripts_save', 'machina_inpost_scripts_nonce' );
	?>

	<p><label for="machina_scripts" class="screen-reader-text"><b><?php _e( 'Page-specific Scripts', 'machina' ); ?></b></label></p>
	<p><textarea class="large-text" rows="4" cols="4" name="machina_seo[_machina_scripts]" id="machina_scripts"><?php echo esc_textarea( machina_get_custom_field( '_machina_scripts' ) ); ?></textarea></p>
	<p><?php printf( __( 'Suitable for custom tracking, conversion or other page-specific script. Must include %s tags.', 'machina' ), machina_code( 'script' ) ); ?></p>
	<?php

}

add_action( 'save_post', 'machina_inpost_scripts_save', 1, 2 );
/**
 * Save the Scripts settings when we save a post or page.
 *
 * @since 2.0.0
 *
 * @uses machina_save_custom_fields() Perform checks and saves post meta / custom field data to a post or page.
 *
 * @param integer  $post_id Post ID.
 * @param stdClass $post    Post object.
 *
 * @return null Returns null if no value POSTed.
 */
function machina_inpost_scripts_save( $post_id, $post ) {

	if ( ! isset( $_POST['machina_seo'] ) )
		return;

	 //* If user doesn't have unfiltered html capability, don't try to save
	if ( ! current_user_can( 'unfiltered_html' ) )
		return;

	//* Merge user submitted options with fallback defaults
	$data = wp_parse_args( $_POST['machina_seo'], array(
		'_machina_scripts' => '',
	) );

	machina_save_custom_fields( $data, 'machina_inpost_scripts_save', 'machina_inpost_scripts_nonce', $post );

}

add_action( 'admin_menu', 'machina_add_inpost_layout_box' );
/**
 * Register a new meta box to the post or page edit screen, so that the user can set layout options on a per-post or
 * per-page basis.
 *
 * @since 0.2.2
 *
 * @see machina_inpost_layout_box() Generates the content in the boxes
 *
 * @return null Returns null if Machina layouts are not supported
 */
function machina_add_inpost_layout_box() {

	if ( ! current_theme_supports( 'machina-inpost-layouts' ) )
		return;

	foreach ( (array) get_post_types( array( 'public' => true ) ) as $type ) {
		if ( post_type_supports( $type, 'machina-layouts' ) )
			add_meta_box( 'machina_inpost_layout_box', __( 'Layout Settings', 'machina' ), 'machina_inpost_layout_box', $type, 'normal', 'default' );
	}

}

/**
 * Callback for in-post layout meta box.
 *
 * @since 0.2.2
 *
 * @uses machina_get_custom_field() Get custom field value.
 * @uses machina_layout_selector()  Layout selector.
 */
function machina_inpost_layout_box() {

	wp_nonce_field( 'machina_inpost_layout_save', 'machina_inpost_layout_nonce' );

	$layout = machina_get_custom_field( '_machina_layout' );

	?>
	<div class="machina-layout-selector">
		<p><input type="radio" name="machina_layout[_machina_layout]" class="default-layout" id="default-layout" value="" <?php checked( $layout, '' ); ?> /> <label class="default" for="default-layout"><?php printf( __( 'Default Layout set in <a href="%s">Theme Settings</a>', 'machina' ), menu_page_url( 'machina', 0 ) ); ?></label></p>

		<p><?php machina_layout_selector( array( 'name' => 'machina_layout[_machina_layout]', 'selected' => $layout, 'type' => 'site' ) ); ?></p>
	</div>

	<br class="clear" />

	<p><label for="machina_custom_body_class"><b><?php _e( 'Custom Body Class', 'machina' ); ?></b></label></p>
	<p><input class="large-text" type="text" name="machina_layout[_machina_custom_body_class]" id="machina_custom_body_class" value="<?php echo esc_attr( machina_get_custom_field( '_machina_custom_body_class' ) ); ?>" /></p>

	<p><label for="machina_custom_post_class"><b><?php _e( 'Custom Post Class', 'machina' ); ?></b></label></p>
	<p><input class="large-text" type="text" name="machina_layout[_machina_custom_post_class]" id="machina_custom_post_class" value="<?php echo esc_attr( machina_get_custom_field( '_machina_custom_post_class' ) ); ?>" /></p>
	<?php

}

add_action( 'save_post', 'machina_inpost_layout_save', 1, 2 );
/**
 * Save the layout options when we save a post or page.
 *
 * Since there's no sanitizing of data, the values are pulled from identically named keys in $_POST.
 *
 * @since 0.2.2
 *
 * @uses machina_save_custom_fields() Perform checks and saves post meta / custom field data to a post or page.
 *
 * @param integer  $post_id Post ID.
 * @param stdClass $post    Post object.
 *
 * @return mixed Returns post id if permissions incorrect, null if doing autosave, ajax or future post, false if update
 *               or delete failed, and true on success.
 *
 */
function machina_inpost_layout_save( $post_id, $post ) {

	if ( ! isset( $_POST['machina_layout'] ) )
		return;

	$data = wp_parse_args( $_POST['machina_layout'], array(
		'_machina_layout'            => '',
		'_machina_custom_body_class' => '',
		'_machina_post_class'        => '',
	) );

	$data = array_map( 'machina_sanitize_html_classes', $data );

	machina_save_custom_fields( $data, 'machina_inpost_layout_save', 'machina_inpost_layout_nonce', $post );

}

