<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Admin
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

/**
 * Registers a new admin page, providing content and corresponding menu item for the "What's new" page.
 *
 * @package Machina\Admin
 *
 * @since 1.9.0
 */
class Machina_Admin_Upgraded extends Machina_Admin_Basic {

	/**
	 * Create the page.
	 *
	 * @uses PARENT_THEME_BRANCH      Machina Framework branch.
	 * @uses \Machina_Admin::create() Register the admin page.
	 *
	 * @since 1.9.0
	 */
	function __construct() {

		$page_id = 'machina-upgraded';

		$menu_ops = array(
			'submenu' => array(
				'parent_slug' => 'admin.php',
				'menu_title'  => '',
				'page_title'  => sprintf( __( 'Welcome to Machina %s', 'machina' ), PARENT_THEME_BRANCH ),
			)
		);

		$this->create( $page_id, $menu_ops );

		add_action( 'admin_enqueue_scripts', 'add_thickbox' );

	}

	/**
	 * Callback for displaying the What's New admin page.
	 *
	 * @since 1.9.0
	 */
	public function admin() {

		?>
		<div class="wrap about-wrap">

		<img src="<?php echo get_template_directory_uri() . '/lib/admin/images/whats-new.png'; ?>" class="alignright whats-new" />

		<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>

		<div class="about-text"><?php printf( __( 'Congratulations! You\'re now running Machina %s.', 'machina' ), PARENT_THEME_BRANCH ); ?></div>

		<div class="changelog">
			<h3><?php _e( 'What&#8217;s New', 'machina' ); ?></h3>
			<div class="feature-section">

				<h4><?php _e( 'HTML5 Markup', 'machina' ); ?></h4>
				<p><?php _e( 'Machina has always been on the cutting edge of web technology, and Machina 2.0 continues in that excellent tradition. With a single line of code in a child theme, Machina will now output HTML5 markup in place of the old XHTML tags. Also, every theme we build in the future will be developed on HTML5.', 'machina' ); ?></p>

				<h4><?php _e( 'Microdata', 'machina' ); ?></h4>
				<p><?php printf( __( 'If you\'re using a theme with HTML5 enabled, Machina will also output your markup using microdata.. Not sure what that is? We don\'t blame you. Take a look at <a href="%s" target="_blank">this explanation</a>. Still confused? Don\'t worry. That\'s why you\'re using a framework. We did all the research and modified the markup to serve search engines the Microdata they\'re looking for, so you don\'t have to. It\'s good to be a Machina user.', 'machina' ), 'http://html5doctor.com/microdata/' ); ?></p>

				<h4><?php _e( 'A Brand New Design', 'machina' ); ?></h4>
				<p><?php _e( 'Machina is sporting a fresh new look. And we\'ve taken advantage of the new HTML5 markup, as well as some snazzy CSS3. We think you\'re gonna love this.', 'machina' ); ?></p>

				<h4><?php _e( 'Removing Features', 'machina' ); ?></h4>
				<p><?php _e( 'We want to keep Machina as lightweight as possible for you, nobody wants to use bloated software. So we\'ve removed the Latest Tweets widget, eNews widget, the "post templates" feature, and the "fancy dropdowns" setting. But fear not! If you want those features back, click below to install the handy plugins we created for you.', 'machina' ); ?></p>

				<p>
					<ul>
						<li><?php echo machina_plugin_install_link( 'machina-latest-tweets', __( 'Machina Latest Tweets Widget', 'machina' ) ); ?></li>
						<li><?php echo machina_plugin_install_link( 'machina-enews-extended', __( 'Machina eNews Extended', 'machina' ) ); ?></li>
						<li><?php echo machina_plugin_install_link( 'single-post-template', __( 'Single Post Template', 'machina' ) ); ?></li>
						<li><?php echo machina_plugin_install_link( 'machina-fancy-dropdowns', __( 'Fancy Dropdowns', 'machina' ) ); ?></li>
					</ul>
				</p>

				<h4><?php _e( 'Boring, but important', 'machina' ); ?></h4>
				<p><?php _e( 'We\'re always improving. Call it a sickness, but we like to make things work really, really well. Here\'s a list of the technical changes in this latest release.', 'machina' ); ?></p>

				<p>
					<ul>
						<li><?php _e( 'Better named loop hooks for HTML5.', 'machina' ); ?></li>
						<li><?php _e( 'Network Upgrade now upgrades the Machina database for all sites in a network when running WordPress in multisite mode.', 'machina' ); ?></li>
						<li><?php _e( 'Widget classes are now coded in PHP5 format.', 'machina' ); ?></li>
						<li><?php _e( 'Admin CSS and Javascript are now minified.', 'machina' ); ?></li>
						<li><?php _e( 'Inline HTML comments have been removed to reduce page size.', 'machina' ); ?></li>
						<li><?php _e( 'The Scripts option now has its own metabox when editing an entry.', 'machina' ); ?></li>
						<li><?php _e( 'Custom Post Type archive pages now have a settings page so you can control the output.', 'machina' ); ?></li>
						<li><?php _e( 'Machina tracks displayed entry IDs so you can exclude entries from showing twice on a page.', 'machina' ); ?></li>
						<li><?php _e( 'Entries without titles now display a permalink after the post content.', 'machina' ); ?></li>
					</ul>
				<p>

				</div>
		</div>

		<div class="return-to-dashboard">
			<p><a href="<?php echo esc_url( menu_page_url( 'machina', 0 ) ); ?>"><?php _e( 'Go to Theme Settings &rarr;', 'machina' ); ?></a></p>
			<p><a href="<?php echo esc_url( menu_page_url( 'seo-settings', 0 ) ); ?>"><?php _e( 'Go to SEO Settings &rarr;', 'machina' ); ?></a></p>
		</div>

		</div>
		<?php

	}

}
