<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Assets
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

add_action( 'machina_meta', 'machina_load_stylesheet' );
/**
 * Echo reference to the style sheet.
 *
 * If a child theme is active, it loads the child theme's stylesheet, otherwise, it loads the Machina style sheet.
 *
 * @since 0.2.2
 *
 * @see machina_enqueue_main_stylesheet() Enqueue main style sheet.
 */
function machina_load_stylesheet() {

	add_action( 'wp_enqueue_scripts', 'machina_enqueue_main_stylesheet', 5 );

}

/**
 * Enqueue main style sheet.
 *
 * Properly enqueue the main style sheet.
 *
 * @since 1.9.0
 *
 * @uses CHILD_THEME_NAME
 * @uses CHILD_THEME_VERSION
 * @uses PARENT_THEME_VERSION
 */
function machina_enqueue_main_stylesheet() {

	$version = defined( 'CHILD_THEME_VERSION' ) && CHILD_THEME_VERSION ? CHILD_THEME_VERSION : PARENT_THEME_VERSION;
	$handle  = defined( 'CHILD_THEME_NAME' ) && CHILD_THEME_NAME ? sanitize_title_with_dashes( CHILD_THEME_NAME ) : 'child-theme';

	wp_enqueue_style( $handle, get_stylesheet_uri(), false, $version );

}

add_action( 'admin_print_styles', 'machina_load_admin_styles' );
/**
 * Enqueue Machina admin styles.
 *
 * @since 0.2.3
 *
 * @uses MACHINA_CSS_URL
 * @uses PARENT_THEME_VERSION
 */
function machina_load_admin_styles() {

	$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';

	wp_enqueue_style( 'machina_admin_css', MACHINA_CSS_URL . "/admin$suffix.css", array(), PARENT_THEME_VERSION );

}

add_action( 'wp_enqueue_scripts', 'machina_load_print_stylesheet' );
/**
 * Set our own action hook for hooking styles in
 *
 * @since 1.5.0
 *
 * @uses  get_stylesheet_directory()
 */
function machina_load_print_stylesheet() {

  /**
   * At first, look in child theme for custom print stylesheet: 'print.css'
   * If it exists, enqueue it!
   */
  if ( is_readable( get_stylesheet_directory() . '/assets/css/print.css' ) ) {

    /* Enqueue child theme print stylesheet. */
    wp_enqueue_style( 'printstyle-child', get_stylesheet_directory_uri() . '/assets/css/print.css', false, defined( 'CHILD_THEME_VERSION' ) ? CHILD_THEME_VERSION : PARENT_THEME_VERSION, 'print' );

  }

  /** If no custom/user stylesheet exists, enqueue our default plugin's print styles */
  else {

    $suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';

    wp_enqueue_style( 'printstyle', MACHINA_CSS_URL . "/print$suffix.css", false, PARENT_THEME_VERSION, 'print' );

  } // end if/else stylesheet file checks

}  // end of function machina_load_print_stylesheet
