<?php
/**
 * This template displays the Download Category and Tag taxonomy term archives in EDD
 *
 * Note for customisers/users: Do not edit this file!
 * ===================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in your child theme's root folder or "edd" subfolder, i.e. /wp-content/themes/your-child-theme/edd
 * (Your theme may not have a "edd" folder, so just create one.)
 * The version in the child theme's root/"edd" folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 * @since 1.0.0
 */

/** Let Machina take over :) */
machina();