<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Breadcrumbs
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

/**
 * Helper function for the Machina Breadcrumb Class.
 *
 * @since 0.1.6
 *
 * @global Machina_Breadcrumb $_machina_breadcrumb
 * @param array $args Breadcrumb arguments
 */
function machina_breadcrumb( $args = array() ) {

	global $_machina_breadcrumb;

	if ( ! $_machina_breadcrumb )
		$_machina_breadcrumb = new Machina_Breadcrumb;

	$_machina_breadcrumb->output( $args );

}

add_action( 'machina_before_loop', 'machina_do_breadcrumbs' );
/**
 * Display Breadcrumbs above the Loop. Concedes priority to popular breadcrumb
 * plugins.
 *
 * @since 0.1.6
 *
 * @return null Return null if a popular breadcrumb plugin is active
 */
function machina_do_breadcrumbs() {

	if (
		( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && ! machina_get_option( 'breadcrumb_home' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && ! machina_get_option( 'breadcrumb_front_page' ) ) ||
		( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && ! machina_get_option( 'breadcrumb_posts_page' ) ) ||
		( is_single() && ! machina_get_option( 'breadcrumb_single' ) ) ||
		( is_page() && ! machina_get_option( 'breadcrumb_page' ) ) ||
		( ( is_archive() || is_search() ) && ! machina_get_option( 'breadcrumb_archive' ) ) ||
		( is_404() && ! machina_get_option( 'breadcrumb_404' ) ) ||
		( is_attachment() && ! machina_get_option( 'breadcrumb_attachment' ) )
	)
		return;

	if ( function_exists( 'bcn_display' ) ) {
		echo '<div class="breadcrumb" itemprop="breadcrumb">';
		bcn_display();
		echo '</div>';
	}
	elseif ( function_exists( 'yoast_breadcrumb' ) ) {
		yoast_breadcrumb( '<div class="breadcrumb">', '</div>' );
	}
	elseif ( function_exists( 'breadcrumbs' ) ) {
		breadcrumbs();
	}
	elseif ( function_exists( 'crumbs' ) ) {
		crumbs();
	}
	else {
		machina_breadcrumb();
	}

}
