<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\Custom
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */


add_action( 'init', 'machina_add_editor_styles' );
/**
 * Apply theme's stylesheet to the visual editor.
 *
 * @todo  kinda works
 *
 * @uses add_editor_style() Links a stylesheet to visual editor
 * @uses get_stylesheet_uri() Returns URI of theme stylesheet
 */
function machina_add_editor_styles() {

	add_editor_style( get_stylesheet_uri() );

}