<?php
/**
 * Machina Framework.
 *
 * WARNING: This file is part of the core Machina Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Machina\SEO
 * @author  MachinaThemes
 * @license GPL-2.0+
 * @link    http://my.machinathemes.com/themes/machina/
 */

/**
 * Disable the Machina SEO features.
 *
 * @since 1.6.0
 *
 * @see machina_default_title()
 * @see machina_doc_head_control()
 * @see machina_seo_meta_description()
 * @see machina_seo_meta_keywords()
 * @see machina_robots_meta()
 * @see machina_canonical()
 * @see machina_add_inpost_seo_box()
 * @see machina_add_inpost_seo_save()
 * @see machina_add_taxonomy_seo_options()
 * @see machina_user_seo_fields()
 *
 * @uses MACHINA_SEO_SETTINGS_FIELD
 */
function machina_disable_seo() {

	remove_filter( 'wp_title', 'machina_default_title', 10, 3 );
	remove_action( 'get_header', 'machina_doc_head_control' );
	remove_action( 'machina_meta','machina_seo_meta_description' );
	remove_action( 'machina_meta','machina_seo_meta_keywords' );
	remove_action( 'machina_meta','machina_robots_meta' );
	remove_action( 'wp_head','machina_canonical', 5 );
	remove_action( 'wp_head', 'machina_rel_author' );

	remove_action( 'admin_menu', 'machina_add_inpost_seo_box' );
	remove_action( 'save_post', 'machina_inpost_seo_save', 1, 2 );

	remove_action( 'admin_init', 'machina_add_taxonomy_seo_options' );

	remove_action( 'show_user_profile', 'machina_user_seo_fields' );
	remove_action( 'edit_user_profile', 'machina_user_seo_fields' );
	remove_filter( 'user_contactmethods', 'machina_user_contactmethods' );

	remove_theme_support( 'machina-seo-settings-menu' );
	add_filter( 'pre_option_' . MACHINA_SEO_SETTINGS_FIELD, '__return_empty_array' );

	define( 'MACHINA_SEO_DISABLED', true );

}

/**
 * Detect whether or not Machina SEO has been disabled.
 *
 * @since 1.8.0
 *
 * @uses MACHINA_SEO_DISABLED
 *
 * @return bool True if Machina SEO is disabled, false otherwise.
 */
function machina_seo_disabled() {

	if ( defined( 'MACHINA_SEO_DISABLED' ) && MACHINA_SEO_DISABLED )
		return true;

	return false;

}

add_action( 'after_setup_theme', 'machina_seo_compatibility_check', 5 );
/**
 * Check for the existence of popular SEO plugins and disable the Machina SEO features if one or more of the plugins
 * is active.
 *
 * Runs before the menu is built, so we can disable SEO Settings menu, if necessary.
 *
 * @since 1.2.0
 *
 * @see machina_default_title()
 *
 * @uses machina_detect_seo_plugins() Detect certain SEO plugins.
 * @uses machina_disable_seo()        Disable all aspects of Machina SEO features.
 */
function machina_seo_compatibility_check() {

	if ( machina_detect_seo_plugins() )
		machina_disable_seo();

	//* Disable Machina <title> generation if SEO Title Tag is active
	if ( function_exists( 'seo_title_tag' ) ) {
		remove_filter( 'wp_title', 'machina_default_title', 10, 3 );
		remove_action( 'machina_title', 'wp_title' );
		add_action( 'machina_title', 'seo_title_tag' );
	}

}

/**
 * Detect some SEO Plugin that add constants, classes or functions.
 *
 * Applies `machina_detect_seo_plugins` filter to allow third party manpulation of SEO plugin list.
 *
 * @since 1.6.0
 *
 * @uses machina_detect_plugin() Detect active plugin by constant, class or function existence.
 *
 * @return boolean True if plugin exists or false if plugin constant, class or function not detected.
 */
function machina_detect_seo_plugins() {

	return machina_detect_plugin(
		// Use this filter to adjust plugin tests.
		apply_filters(
			'machina_detect_seo_plugins',
			//* Add to this array to add new plugin checks.
			array(

				// Classes to detect.
				'classes' => array(
					'All_in_One_SEO_Pack',
					'All_in_One_SEO_Pack_p',
					'HeadSpace_Plugin',
					'Platinum_SEO_Pack',
					'wpSEO',
					'SEO_Ultimate',
				),

				// Functions to detect.
				'functions' => array(),

				// Constants to detect.
				'constants' => array( 'WPSEO_VERSION', ),
			)
		)
	);

}
