<?php
/*
 WARNING: DO NOT edit this file under any circumstances.
 Please do all PHP modifications via the Custom Code admin menu.
*/

/**
 * This file calls the init.php file for both Machina and Prose.
 *
 * It initializes the Machina framework, and loads the Prose library as well.
 *
 * This file is a core Prose file and should not be edited.
 *
 * @author   Machina Themes
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.machinathemes.com/themes/machina
 */



prose_create_custom_php();